#if !canImport(ObjectiveC)
import XCTest

extension FlockServerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlockServerTests = [
        ("testFlockServer", testFlockServer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FlockServerTests.__allTests__FlockServerTests),
    ]
}
#endif
