#if !canImport(ObjectiveC)
import XCTest

extension FlockClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlockClientTests = [
        ("testFlockClient", testFlockClient),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FlockClientTests.__allTests__FlockClientTests),
    ]
}
#endif
